### ISSUE TITLE
mic button does not work as intended

### ISSUE THREAD

**Issue by AntonBiryukovUofC** [miguelgrinberg/socketio-examples#1]
Hello @miguelgrinberg , and thanks for providing examples of how to use WebSocket with Flask.

I am trying to use your audio example, and modify it to my particular situation where all i need is a microphone recording button, and then saving that record into `static/_files` folder or any other folder. 
But somehow when i click the microphone button, nothing happens and no files appear under static. However, I do see the stream in the top panel as i speak into the mic.

I have also noticed that functions defined in `audio.py` are not actually called while the app is running (particularly those that are callbacks to `onclick`). 
My JS knowledge is virtually non-existent unfortunately, and there might be something I am misunderstanding here. I was probably too optimistic to think that Python here might be enough :)

But I still hope you can help me out.

I am working under Win 10, Flask 1.0.2

Thanks,
Anton.

**Comment by miguelgrinberg** [comment]
This is an application that uses both JavaScript and Python, so you are going to need to debug from both sides to figure out where is the problem. For example, if you look in your browser's console, are there any error messages? And what about in your Python terminal?

**Comment by AntonBiryukovUofC** [comment]
So I did plug in a few statement with console.log() in the JS part, and print statements in the python side. I do see confirmation that the clicks on the mic icon are processed properly -> the messages are printed in the browser console.

However, on the python side I do not see the code entering the emit part.

I played with it on my Linux machine, and brought the @socketio statements, along with the necessary imports into the main app script file, and it started magically working somehow. So it seems to me either namespaces or something else is off here... :(

**Comment by miguelgrinberg** [comment]
@AntonBiryukovUofC are you saying that the application works on Linux but not on Windows 10? The same app, without any changes?

**Comment by AntonBiryukovUofC** [comment]
Have not tried yet under Win 10 machine, in the progress still. I would like though to understand how to keep it "modular", the way you initially built it. It just looks much nicer that way, instead of my brute-force copy-pasting and hacking it.

**Comment by AntonBiryukovUofC** [comment]
broke the blueprint down, and carried the socketio functions into the main app - everything works under both platforms. Still confused as to why the functions did not work when they were sitting in a separate source file.

**Comment by miguelgrinberg** [comment]
I'm not sure why the structure is in this repository would not work. Have you made any changes? I've used this application as it is and did not have any problems.
