### ISSUE TITLE
Audio, file uploads doesn't work

### ISSUE THREAD

**Issue by saadatzi** [miguelgrinberg/socketio-examples#2]
Hi

The Audio part records the voice but it doesn't upload the recorded file.
Neither upload part upload the selected files, I mean it doesn't show the any bar that it has been uploaded besides you cannot find the files in any folder.

**Comment by miguelgrinberg** [comment]
This code works fine, I demoed it live at a presentation. What we need to find out is why it does not work for you. Are you using the same dependencies, as shown in the requirements file? Do you get any error messages in your console or log? Any errors in the browser console or network tab?

**Comment by saadatzi** [comment]
I have this error on my chrome and firefox Console:

WebSocket connection to 'ws://127.0.0.1:5000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

Thanks for your help

**Comment by saadatzi** [comment]
It also says : Warning in __init__ : Flask-socketIO is Running under Werkzeug , Websocket is not available.

**Comment by saadatzi** [comment]
Replaced my existing Flask-socketIO to 3.1.2 version and it worked.
It was Crazy dude by the way, Why it should be like that.

**Comment by miguelgrinberg** [comment]
As I said, this example was created a couple of years ago, and it works with the requirements that are defined. If you want to use newer dependencies there might be some minor changes needed. The 400 is probably related to CORS, an area that has seen some improvements.

The WebSocket not available is likely that you are not installing all the needed dependencies. My guess is that you missed to install eventlet.
