### ISSUE TITLE
Recording audio from client's side.

### ISSUE THREAD

**Issue by sucream1004** [miguelgrinberg/socketio-examples#3]
Hi,

Firstly, thanks for the example. I am a newbie and learning coding things myself. I am trying to record audio from the client side. Is it possible using flask and socketio?

**Comment by miguelgrinberg** [comment]
Well, the audio example in this repository does just that. Do you have a specific question about it?

**Comment by sucream1004** [comment]
Thanks for the reply. Since I am a super beginner, I misunderstood. Actually, it's working well. My problem is due to the https certificate(it seems like the privacy issue?). I tested to record using another computer.
