### ISSUE TITLE
How to achieve sliding window on live stream?

### ISSUE THREAD

**Issue by sainimohit23** [miguelgrinberg/socketio-examples#5]
Hi @miguelgrinberg , I am working on an application where I have to do some predictions on live audio stream using a deep learning model. The model expects the 10 second audio as input. 

So, I want to update the 10 second input audio every 0.5 seconds. That means the initial 0.5 second chunk of input 10 second audio will be discarded and the new 0.5 second audio will be appended to our input. Can you guide me on how to achieve something similar?

**Comment by miguelgrinberg** [comment]
I don't have anything specific to give you, but if your audio is going to be some sort of array (maybe a numpy array?) you can use normal array operations to remove elements from the start and append elements at the end.

**Comment by sainimohit23** [comment]
Thanks for replying @miguelgrinberg . Is there any way to provide a callback function to do the array operations on the input stream? From what I can understand from the example is that I can access the  `session['wavefile']` only after I end the recording.

**Comment by sainimohit23** [comment]
I think I can do one thing. I can set a timer using javascript that will call a function. And that function can be used to trim audio in regular intervals of time.

**Comment by miguelgrinberg** [comment]
No, you are mistaken. There is already a callback that receives buffers of audio in real time. See https://github.com/miguelgrinberg/socketio-examples/blob/master/audio/audio.py#L37.

**Comment by sainimohit23** [comment]
Got it. One more thing, your Flask tutorial is brilliant. Right now I am on chapter 13 and I am really loving it. Thanks for all your work. Closing this issue.
