### ISSUE TITLE
Audio application

### ISSUE THREAD

**Issue by asyrafzlkln96** [miguelgrinberg/socketio-examples#6]
Hi, I want to ask.
The audio application has recording function only right?
But nothing is happening when tried to record from my mic?

Thanks.
Asyraf.

**Comment by miguelgrinberg** [comment]
What do you mean by "nothing happened"? The audio is streamed to the server, which records it to a .wav file. That's what should happen.

**Comment by dyannethorne** [comment]
Can I know how to access the server?

**Comment by dyannethorne** [comment]
Can I know where does it store recorded audio?

**Comment by miguelgrinberg** [comment]
In the `/static/_files` directory.
